sonar.projectKey=samyak-w_pulseapi
sonar.organization=samyak-w
sonar.projectName=PulseAPI Backend
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/coverage/**,**/data/**
sonar.sourceEncoding=UTF-8
